#!/usr/bin/env python3
"""
简化的MySQL到PostgreSQL SQL转换工具
"""

import re
import sys
from pathlib import Path

def convert_mysql_to_postgresql(input_file, output_file):
    """转换MySQL SQL为PostgreSQL格式"""
    
    print(f"开始转换: {input_file}")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"原始文件大小: {len(content)} 字符")
    
    # 转换规则
    conversions = [
        # 反引号替换为双引号
        (r'`([^`]+)`', r'"\1"'),
        
        # 数据类型转换
        (r'int\(\d+\)', 'integer'),
        (r'varchar\(\d+\)', 'text'),
        (r'datetime', 'timestamp'),
        (r'timestamp\(\d+\)', 'timestamp'),
        (r'text', 'text'),
        (r'longtext', 'text'),
        
        # 删除MySQL特有的语法
        (r'ENGINE=InnoDB', ''),
        (r'DEFAULT CHARSET=utf8mb4', ''),
        (r'COLLATE=utf8mb4_unicode_ci', ''),
        (r'COLLATE=utf8mb4_general_ci', ''),
        
        # 自增语法转换
        (r'AUTO_INCREMENT', 'GENERATED BY DEFAULT AS IDENTITY'),
        
        # 注释语法调整
        (r'COMMENT\s+\'([^\']*)\'', r'-- \1'),
        
        # 移除多余的空行
        (r'\n\s*\n\s*\n', '\n\n'),
    ]
    
    # 应用转换规则
    for pattern, replacement in conversions:
        content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)
    
    # 清理多余的空格
    content = re.sub(r'\s+', ' ', content)
    content = re.sub(r';\s*', ';\n', content)
    
    # 保存转换后的文件
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"转换完成: {output_file}")
    print(f"转换后文件大小: {len(content)} 字符")

def main():
    """主函数"""
    input_file = r"E:\DATA\20250725\travelindustry.sql"
    output_file = r"E:\DATA\20250725\travelindustry_supabase.sql"
    
    if not Path(input_file).exists():
        print(f"错误: 输入文件 {input_file} 不存在")
        return
    
    try:
        convert_mysql_to_postgresql(input_file, output_file)
        print("\n✅ 转换完成！")
        print(f"输出文件: {output_file}")
        print("\n下一步:")
        print("1. 在Supabase SQL Editor中执行转换后的SQL文件")
        print("2. 检查导入结果")
    except Exception as e:
        print(f"转换过程中发生错误: {e}")

if __name__ == "__main__":
    main() 