#!/usr/bin/env python3
"""
修复PostgreSQL语法错误
"""

import re
from pathlib import Path

def fix_postgresql_syntax(input_file, output_file):
    """修复PostgreSQL语法错误"""
    
    print(f"开始修复语法: {input_file}")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 修复语法错误
    fixes = [
        # 移除MySQL特有的语法
        (r'ENGINE=InnoDB', ''),
        (r'DEFAULT CHARSET=utf8mb4', ''),
        (r'COLLATE=utf8mb4_0900_ai_ci', ''),
        (r'COLLATE=utf8mb4_unicode_ci', ''),
        (r'COLLATE=utf8mb4_general_ci', ''),
        
        # 修复默认值语法
        (r"DEFAULT '(\d+)'", r"DEFAULT \1"),
        
        # 修复时间戳默认值
        (r"DEFAULT 'CURRENT_TIMESTAMP'", "DEFAULT CURRENT_TIMESTAMP"),
        (r"DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'", "DEFAULT CURRENT_TIMESTAMP"),
        
        # 移除MySQL注释
        (r'/\*![^*]*\*/', ''),
        
        # 修复外键语法
        (r'CONSTRAINT `([^`]+)` FOREIGN KEY', r'CONSTRAINT "\1" FOREIGN KEY'),
        (r'REFERENCES `([^`]+)` \(`([^`]+)`\)', r'REFERENCES "\1" ("\2")'),
    ]
    
    # 应用修复
    for pattern, replacement in fixes:
        content = re.sub(pattern, replacement, content, flags=re.IGNORECASE)
    
    # 特殊处理：修复IDENTITY语法
    # 将 GENERATED BY DEFAULT AS IDENTITY=数字 替换为 SERIAL
    content = re.sub(r'"id"\s+int\s+NOT\s+NULL\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY[^,)]*', '"id" SERIAL', content, flags=re.IGNORECASE)
    
    # 移除表末尾的 GENERATED BY DEFAULT AS IDENTITY=数字
    content = re.sub(r'\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY=\d+', '', content, flags=re.IGNORECASE)
    
    # 清理多余的空格和换行
    content = re.sub(r'\s+', ' ', content)
    content = re.sub(r';\s*', ';\n', content)
    content = re.sub(r'\n\s*\n', '\n\n', content)
    
    # 保存修复后的文件
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"语法修复完成: {output_file}")

def main():
    """主函数"""
    input_file = r"E:\DATA\20250725\travelindustry_supabase.sql"
    output_file = r"E:\DATA\20250725\travelindustry_supabase_fixed.sql"
    
    if not Path(input_file).exists():
        print(f"错误: 输入文件 {input_file} 不存在")
        return
    
    try:
        fix_postgresql_syntax(input_file, output_file)
        print("\n✅ 语法修复完成！")
        print(f"修复后的文件: {output_file}")
        print("\n现在可以重新运行分割脚本:")
        print("python split_sql.py")
    except Exception as e:
        print(f"修复过程中发生错误: {e}")

if __name__ == "__main__":
    main() 