#!/usr/bin/env python3
"""
简单的PostgreSQL语法修复
"""

def fix_sql_file():
    input_file = r"E:\DATA\20250725\travelindustry_supabase.sql"
    output_file = r"E:\DATA\20250725\travelindustry_supabase_fixed.sql"
    
    print(f"开始修复: {input_file}")
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"原始文件大小: {len(content)} 字符")
        
        # 简单的字符串替换
        replacements = [
            ('ENGINE=InnoDB', ''),
            ('DEFAULT CHARSET=utf8mb4', ''),
            ('COLLATE=utf8mb4_0900_ai_ci', ''),
            ('COLLATE=utf8mb4_unicode_ci', ''),
            ('COLLATE=utf8mb4_general_ci', ''),
            ("DEFAULT '0'", 'DEFAULT 0'),
            ("DEFAULT '1'", 'DEFAULT 1'),
            ("DEFAULT 'CURRENT_TIMESTAMP'", 'DEFAULT CURRENT_TIMESTAMP'),
            ('GENERATED BY DEFAULT AS IDENTITY=229', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=230', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=231', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=232', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=233', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=234', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=235', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=236', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=237', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=238', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=239', ''),
            ('GENERATED BY DEFAULT AS IDENTITY=240', ''),
        ]
        
        for old, new in replacements:
            content = content.replace(old, new)
        
        # 修复ID字段
        content = content.replace('"id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY', '"id" SERIAL')
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"修复完成: {output_file}")
        print(f"修复后文件大小: {len(content)} 字符")
        
    except Exception as e:
        print(f"错误: {e}")

if __name__ == "__main__":
    fix_sql_file() 